---
- name: Install packages
  apt:
    name:
        - apt-listbugs
        - apt-listchanges
        - docker.io
        - firefox-esr
        - git
        - grub-customizer
        - htop
        - keepassxc
        - vim
        - zulucrypt-gui
        - virt-manager
    autoclean: True
    autoremove: True
    force_apt_get: True
    update_cache: True
    cache_valid_time: 3600
    install_recommends: False
  become: true
