- name: ensure default sources.list is removed
  file:
    state: absent
    path: /etc/apt/sources.list
  become: True
  notify: update apt repository cache


- name: ensure apt repositories are managed
  apt_repository:
    state: present
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    validate_certs: True
    update_cache: True
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: True
  with_items:
    - "{{ apt_repo_repositories }}"
  notify: update apt repository cache

# Make sure the handler runs now and not at the end of the playbook
- meta: flush_handlers
